export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'
export const REQUEST_ITEMS_PENDING = 'REQUEST_ITEMS_PENDING'
export const REQUEST_ITEMS_SUCCESS = 'REQUEST_ITEMS_SUCCESS'
export const REQUEST_ITEMS_FAILED = 'REQUEST_ITEMS_FAILED'